### PR TITLE
fix(blocks): AudioSink channels

### LINKED ISSUE #3: AudioSink StreamConfigNotSupported on MS/Windows
On MS/Windows, one may encounter the following error message:
```
thread 'smol-5' panicked at 'could not build output stream: StreamConfigNotSupported', C:\Users\loic\.cargo\git\checkouts\futuresdr-09d3094b066a1547\e2bfac0\src\blocks\audio\audio_sink.rs:141:14
```

It is somehow related to [cpal issue #593](https://github.com/RustAudio/cpal/issues/593). Solving the sample rate problem may not be enough as I encounter similar message when requesting a unique channel where the audio driver requires two...

### PR DESCRIPTION
**Pull request by loic-fejoz**
Duplicate input stream of AudioSink in case the configuration stream's channels number is greater than the requested channels.
Related to #3

### CODE REVIEW

**Comment by loic-fejoz** [comment]
Related to https://github.com/FutureSDR/FutureSDR/pull/110

**Comment by bastibl** [comment]
Forking the block just makes things worse. Why can't you just iterate through valid cpal configs and if there is no config that supports mono, fsdr-cli adds a ApplyNM block to convert from mono to stereo and instantiate as a stereo sink. I don't see a reason why a GRC config parameter has to be blindly copied to a FutureSDR block and expect the block to deal with it, even if the parameter is not supported by the underlying audio subsystem.

**Comment by loic-fejoz** [comment]
@bastibl just for quick convenience.
I want something that works for basic demodulation before doing some refactoring that would allow the conversion from one GRC block to several FutureSDR blocks.
So indeed no reason 😃

**Comment by loic-fejoz** [comment]
Said otherwise @bastibl , expect some refactoring and other pull requests later.

**Pull request merged**
